const titles = [
  "The Grudge",
  "Underwater",
  "Like a Boss",
  "Three Christs",
  "Inherit the Viper",
  "The Sonata",
  "The Murder of Nicole Brown Simpson",
  "Bad Boys for Life",
  "Dolittle",
  "A Fall from Grace",
  "The Gentlemen",
  "The Turning",
  "The Last Full Measure",
  "John Henry",
  "The Rhythm Section",
  "Gretel & Hansel",
  "The Assistant",
  "Birds of Prey",
  "The Lodge",
  "Timmy Failure: Mistakes Were Made",
  "Horse Girl",
  "To All the Boys: P.S. I Still Love You",
  "Sonic the Hedgehog",
  "Fantasy Island",
  "The Photograph",
  "Downhill",
  "Spy Intervention",
  "The Kindness of Strangers",
  "The Call of the Wild",
  "Emma",
  "The Last Thing He Wanted",
  "Brahms: The Boy II",
  "The Night Clerk",
  "Impractical Jokers: The Movie",
  "The Invisible Man",
  "All the Bright Places",
  "Wendy",
  "Guns Akimbo",
  "Onward",
  "The Way Back",
  "Spenser Confidential",
  "The Banker",
  "The Burnt Orange Heresy",
  "Swallow",
  "First Cow",
  "Bloodshot",
  "The Hunt",
  "I Still Believe",
  "Lost Girls",
  "Stargirl",
  "The Roads Not Taken",
  "Never Rarely Sometimes Always",
  "Big Time Adolescence",
  "Lost Transmissions",
  "Resistance",
  "Uncorked",
  "Vivarium",
  "Coffee & Kareem",
  "Trolls World Tour",
  "Love Wedding Repeat",
  "The Main Event",
  "We Summon the Darkness",
  "The Lost Husband",
  "Corona Zombies",
  "Sergio",
  "The Willoughbys",
  "Extraction",
  "Braking for Whales",
  "Bad Education",
  "Dangerous Lies",
  "All Day and a Night",
  "The Wretched",
  "The Half of It",
  "Arkansas",
  "Valley Girl",
  "Capone",
  "The Wrong Missy",
  "Scoob!",
  "Blood and Money",
  "Body Cam",
  "The Lovebirds",
  "Inheritance",
  "Survive the Night",
  "The Wanting Mare",
  "The High Note",
  "Shirley",
  "The Last Days of American Crime",
  "Becky",
  "Think Like a Dog",
  "Da 5 Bloods",
  "Artemis Fowl",
  "The King of Staten Island",
  "Sniper: Assassin's End",
  "You Should Have Left",
  "Wasp Network",
  "Feel the Beat",
  "7500",
  "Athlete A",
  "Eurovision Song Contest: The Story of Fire Saga",
  "Irresistible",
  "My Spy",
  "We Bare Bears: The Movie",
  "Hamilton",
  "Relic",
  "Desperados",
  "The Old Guard",
  "Money Plane",
  "Greyhound",
  "Palm Springs",
  "Fatal Affair",
  "The Silencing",
  "A Nice Girl Like You",
  "Ghosts of War",
  "Animal Crackers",
  "The Kissing Booth 2",
  "The Rental",
  "Deep Blue Sea 3",
  "Black Is King",
  "The Secret: Dare To Dream",
  "Summerland",
  "She Dies Tomorrow",
  "An American Pickle",
  "The Tax Collector",
  "Waiting for the Barbarians",
  "Project Power",
  "The SpongeBob Movie: Sponge on the Run (Canadian theatrical release)",
  "Magic Camp",
  "Spree",
  "Boys State",
  "The One and Only Ivan",
  "Unhinged",
  "Tesla",
  "Cut Throat City",
  "Words on Bathroom Walls",
  "Hard Kill",
  "Chemical Hearts",
  "Tenet",
  "Bill & Ted Face the Music",
  "The New Mutants",
  "The Personal History of David Copperfield",
  "I'm Thinking of Ending Things",
  "Phineas and Ferb the Movie: Candace Against the Universe",
  "All Together Now",
  "Rogue",
  "Centigrade",
  "Fatima",
  "All Together Now",
  "Love, Guaranteed",
  "Mulan",
  "Critical Thinking",
  "The Owners",
  "Guest House",
  "The Babysitter: Killer Queen",
  "Unpregnant",
  "The Devil All the Time",
  "The Broken Hearts Gallery",
  "I Met a Girl",
  "Rent-A-Pal",
  "Cats & Dogs 3: Paws Unite!",
  "The Secrets We Keep",
  "Antebellum",
  "The Nest",
  "Blackbird",
  "Lost Girls & Love Hotels",
  "Killian & the Comeback Kids",
  "Enola Holmes",
  "The Trial of the Chicago 7",
  "Ava",
  "Kajillionaire",
  "The Last Shift",
  "Secret Society of Second-Born Royals",
  "She's in Portland",
  "Sightless",
  "The Boys in the Band",
  "The Glorias",
  "On the Rocks",
  "Spontaneous",
  "Vampires vs. the Bronx",
  "Possessor",
  "Death of Me",
  "The Call",
  "American Pie Presents: Girls' Rules",
  "The Lie",
  "Black Box",
  "Hubie Halloween",
  "Books of Blood",
  "Charm City Kings",
  "The War with Grandpa",
  "A Rainy Day in New York",
  "Yellow Rose",
  "The 40-Year-Old Version",
  "Nocturne",
  "Evil Eye",
  "A Babysitter's Guide to Monster Hunting",
  "Love and Monsters",
  "Honest Thief",
  "Clouds",
  "The Devil Has a Name",
  "The Kid Detective",
  "Alone",
  "2 Hearts",
  "The Opening Act",
  "Tremors: Shrieker Island",
  "The Witches",
  "Over the Moon",
  "Borat Subsequent Moviefilm",
  "After We Collided",
  "The Empty Man",
  "Synchronic",
  "Bad Hair",
  "Friendsgiving",
  "The Craft: Legacy",
  "Holidate",
  "Come Play",
  "His House",
  "Spell",
  "Jungleland",
  "Let Him Go",
  "The Informer",
  "The Dark and the Wicked",
  "Hillbilly Elegy",
  "Mank",
  "Freaky",
  "Jingle Jangle: A Christmas Journey",
  "Dreamland",
  "Fatman",
  "The Life Ahead",
  "The Climb",
  "Chick Fight",
  "The Princess Switch: Switched Again",
  "Run",
  "Sound of Metal",
  "The Last Vermeer",
  "Jiu Jitsu",
  "Buddy Games",
  "The Croods: A New Age",
  "Happiest Season",
  "Ma Rainey's Black Bottom",
  "The Christmas Chronicles 2",
  "Uncle Frank",
  "Folklore: The Long Pond Studio Sessions",
  "Superintelligence",
  "Life in a Year",
  "Black Beauty",
  "The Prom",
  "All My Life",
  "Godmothered",
  "Half Brothers",
  "Wander",
  "Black Bear",
  "Let Them All Talk",
  "The Midnight Sky",
  "Songbird",
  "Wild Mountain Thyme",
  "Safety",
  "Wander Darkly",
  "I'm Your Woman",
  "The Stand In",
  "Archenemy",
  "Farewell Amor",
  "Monster Hunter",
  "Greenland",
  "Fatale",
  "Skylines",
  "Hunter Hunter",
  "Breach",
  "Ariana Grande: Excuse Me, I Love You",
  "Sylvie's Love",
  "Wonder Woman 1984",
  "Soul",
  "We Can Be Heroes",
  "News of the World",
  "One Night in Miami...",
  "Promising Young Woman",
  "Pieces of a Woman",
  "Shadow in the Cloud",
  "The White Tiger",
  "Locked Down",
  "The Dig",
  "Outside the Wire",
  "The Marksman",
  "The Ultimate Playlist of Noise",
  "American Skin",
  "Don't Tell a Soul",
  "Our Friend",
  "No Man's Land",
  "Born a Champion",
  "Wrong Turn",
  "Penguin Bloom",
  "The Little Things",
  "Finding ʻOhana",
  "Nomadland",
  "Malcolm & Marie",
  "Palmer",
  "Falling",
  "Bliss",
  "Little Fish",
  "Son of the South",
  "PVT Chat",
  "Music",
  "Judas and the Black Messiah",
  "The Mauritanian",
  "Breaking News in Yuba County",
  "Barb and Star Go to Vista Del Mar",
  "Minari",
  "To All the Boys: Always and Forever",
  "The World to Come",
  "French Exit",
  "Land",
  "Willy's Wonderland",
  "The Map of Tiny Perfect Things",
  "Fear of Rain",
  "I Care a Lot",
  "Flora & Ulysses",
  "Silk Road",
  "Tom & Jerry",
  "The United States vs. Billie Holiday",
  "Cherry",
  "Crisis",
  "Billie Eilish: The World's a Little Blurry",
  "The Vigil",
  "Moxie",
  "Coming 2 America",
  "The SpongeBob Movie: Sponge on the Run",
  "Raya and the Last Dragon",
  "Chaos Walking",
  "Boss Level",
  "Boogie",
  "Yes Day",
  "Long Weekend",
  "Cosmic Sin",
  "Trust",
  "Zack Snyder's Justice League",
  "The Courier",
  "City of Lies",
  "Happily",
  "Nobody",
  "Bad Trip",
  "The Seventh Day",
  "Senior Moment",
  "Godzilla vs. Kong",
  "Concrete Cowboy",
  "The Unholy",
  "Every Breath You Take",
  "Shiva Baby",
  "The Girl Who Believes in Miracles",
  "The Believer",
  "Dawn of the Beast",
  "Voyagers",
  "Thunder Force",
  "Arlo the Alligator Boy",
  "Monday",
  "In the Earth",
  "Stowaway",
  "Mortal Kombat",
  "The Mitchells vs. the Machines",
  "Vanquish",
  "Together Together",
  "We Broke Up",
  "The Deep Ones",
  "Things Heard & Seen",
  "Without Remorse",
  "The Virtuoso",
  "Four Good Days",
  "Separation",
  "The Resort",
  "Wrath of Man",
  "Monster",
  "The Paper Tigers",
  "Mainstream",
  "The Water Man",
  "Here Today",
  "Above Suspicion",
  "Reboot Camp",
  "Benny Loves You",
  "Oxygen",
  "Army of the Dead",
  "Those Who Wish Me Dead",
  "The Woman in the Window",
  "Spiral",
  "Georgetown",
  "Finding You",
  "The Killing of Two Lovers",
  "616 Wilford Lane",
  "Dream Horse",
  "Blast Beat",
  "A Quiet Place Part II",
  "Cruella",
  "Plan B",
  "Changing the Game",
  "Spirit Untamed",
  "The Conjuring: The Devil Made Me Do It",
  "Gully",
  "Flashback",
  "Under the Stadium Lights",
  "Grace and Grit",
  "Awake",
  "Infinite",
  "Peter Rabbit 2: The Runaway",
  "In the Heights",
  "Wish Dragon",
  "The Misfits",
  "12 Mighty Orphans",
  "The House Next Door: Meet the Blacks 2",
  "Queen Bees",
  "DOMINO: Battle of the Bones",
  "Hitman's Wife's Bodyguard",
  "Luca",
  "Fatherhood",
  "The Birthday Cake",
  "Rita Moreno: Just a Girl Who Decided to Go for It",
  "The Sparks Brothers",
  "Truman & Tennessee: An Intimate Conversation",
  "Stalker",
  "Love Spreads",
  "A Crime on the Bayou",
  "Good on Paper",
  "F9",
  "The Ice Road",
  "Werewolves Within",
  "False Positive",
  "Lansky",
  "I Carry You with Me",
  "Mary J. Blige's My Life",
  "Fathom",
  "Rollers",
  "America: The Motion Picture",
  "Zola",
  "No Sudden Move",
  "The Tomorrow War",
  "The Boss Baby: Family Business",
  "The Forever Purge",
  "Fear Street Part One: 1994",
  "Summer of Soul",
  "Till Death",
  "Let Us In",
  "Black Widow",
  "Fear Street Part Two: 1978",
  "Summertime",
  "Gunpowder Milkshake",
  "Space Jam: A New Legacy",
  "Escape Room: Tournament of Champions",
  "Fear Street Part Three: 1666",
  "Die in a Gunfight",
  "Pig",
  "Out of Death",
  "Roadrunner: A Film About Anthony Bourdain",
  "How It Ends",
  "Trollhunters: Rise of the Titans",
  "Snake Eyes",
  "Old",
  "Joe Bell",
  "Jolt",
  "Midnight in the Switchgrass",
  "Broken Diamonds",
  "Val",
  "Ailey",
  "Jungle Cruise",
  "Vivo",
  "Stillwater",
  "The Green Knight",
  "Nine Days",
  "Ride the Eagle",
  "The Evening Hour",
  "Lorelei",
  "Enemies of the State",
  "The Suicide Squad",
  "Naked Singularity",
  "John and the Hole",
  "Playing God",
  "Swan Song",
  "She Ball",
  "The Kissing Booth 3",
  "Homeroom",
  "Free Guy",
  "Respect",
  "Beckett",
  "Don't Breathe 2",
  "CODA",
  "Not Going Quietly",
  "PAW Patrol: The Movie",
  "Reminiscence",
  "The Protégé",
  "Sweet Girl",
  "The Loud House Movie",
  "The Night House",
  "Flag Day",
  "Cryptozoo",
  "Habit",
  "Demonic",
  "Risen",
  "The Witcher: Nightmare of the Wolf",
  "Really Love",
  "Candyman",
  "Vacation Friends",
  "He's All That",
  "No Man of God",
  "Rushed",
  "Afterlife of the Party",
  "Shang-Chi and the Legend of the Ten Rings",
  "Cinderella",
  "Worth",
  "The Gateway",
  "Wild Indian",
  "We Need to Do Something",
  "Kate",
  "Everybody's Talking About Jamie",
  "Malignant",
  "Queenpins",
  "The Card Counter",
  "Come from Away",
  "The Voyeurs",
  "Small Engine Repair",
  "Language Lessons",
  "Show Me the Father",
  "Catch the Bullet",
  "Dating and New York",
  "Bad Candy",
  "Generation Wrecks",
  "My Son",
  "Nightbooks",
  "The Starling",
  "The Eyes of Tammy Faye",
  "Cry Macho",
  "Copshop",
  "Blue Bayou",
  "Prisoners of the Ghostland",
  "Best Sellers",
  "Lady of the Manor",
  "The Nowhere Inn",
  "My Name is Pauli Murray",
  "The Killing of Kenneth Chamberlain",
  "Intrusion",
  "My Little Pony: A New Generation",
  "Dear Evan Hansen",
  "The Guilty",
  "Birds of Paradise",
  "After We Fell",
  "Venom: Let There Be Carnage",
  "The Many Saints of Newark",
  "The Addams Family 2",
  "Bingo Hell",
  "Black as Night",
  "Old Henry",
  "The Jesus Music",
  "Mayday",
  "God's Not Dead: We the People",
  "There's Someone Inside Your House",
  "No Time to Die",
  "Mass",
  "South of Heaven",
  "The Manor",
  "Madres",
  "Justin Bieber: Our World",
  "Survive the Game",
  "Halloween Kills",
  "The Last Duel",
  "Needle in a Timestack",
  "Hard Luck Love Song",
  "Introducing, Selma Blair",
  "The Velvet Underground",
  "Night Teeth",
  "Dune",
  "Ron's Gone Wrong",
  "The French Dispatch",
  "The Harder They Fall",
  "The Electrical Life of Louis Wain",
  "Warning",
  "Passing",
  "Hypnotic",
  "Antlers",
  "Army of Thieves",
  "A Mouthful of Air",
  "The Souvenir Part II",
  "Paranormal Activity: Next of Kin",
  "The Spine of Night",
  "Violet",
  "Heart of Champions",
  "Eternals",
  "Red Notice",
  "Finch",
  "Spencer",
  "Dangerous",
  "Love Hard",
  "The Beta Test",
  "Clifford the Big Red Dog",
  "Tick, Tick... Boom!",
  "Home Sweet Home Alone",
  "Apex",
  "The Power of the Dog",
  "Bruised",
  "The Princess Switch 3: Romancing the Star",
  "Ghostbusters: Afterlife",
  "King Richard",
  "Extinct",
  "C'mon C'mon",
  "Black Friday",
  "Zeros and Ones",
  "Friend of the World",
  "Encanto",
  "House of Gucci",
  "The Unforgivable",
  "Resident Evil: Welcome to Raccoon City",
  "8-Bit Christmas",
  "The Humans",
  "South Park: Post Covid",
  "Licorice Pizza",
  "Single All the Way",
  "Back to the Outback",
  "Diary of a Wimpy Kid",
  "Encounter",
  "Mixtape",
  "Deadlock",
  "West Side Story",
  "Don't Look Up",
  "National Champions",
  "Being the Ricardos",
  "Red Rocket",
  "The Hating Game",
  "Rumble",
  "South Park: Post Covid: The Return of Covid",
  "Spider-Man: No Way Home",
  "Nightmare Alley",
  "The Lost Daughter",
  "Swan Song",
  "The Tender Bar",
  "Mother/Android",
  "Fortress",
  "Sing 2",
  "The Matrix Resurrections",
  "The King's Man",
  "The Tragedy of Macbeth",
  "A Journal for Jordan",
  "American Underdog",
  "Memoria",
  "The 355",
  "The Legend of La Llorona",
  "The Commando",
  "American Siege",
  "Scream",
  "Hotel Transylvania: Transformania",
  "Shattered",
  "The Royal Treatment",
  "Redeeming Love",
  "The King's Daughter",
  "The Tiger Rising",
  "Hellblazers",
  "The Fallout",
  "Home Team",
  "The Ice Age Adventures of Buck Wild",
  "Clean",
  "Sundown",
  "Jackass Forever",
  "Moonfall",
  "Last Looks",
  "The Long Night",
  "Kimi",
  "Shut In",
  "Death on the Nile",
  "Marry Me",
  "Blacklight",
  "I Want You Back",
  "Tall Girl 2",
  "The Sky Is Everywhere",
  "The In Between",
  "Fistful of Vengeance",
  "Uncharted",
  "Dog",
  "Texas Chainsaw Massacre",
  "The Cursed",
  "A Fairy Tale After All",
  "Cyrano",
  "Studio 666",
  "A Madea Homecoming",
  "No Exit",
  "Gasoline Alley",
  "The Batman",
  "After Yang",
  "Fresh",
  "A Day to Die",
  "The Adam Project",
  "Turning Red",
  "Tyson's Run",
  "Rescued by Ruby",
  "The Outfit",
  "Deep Water",
  "Cheaper by the Dozen",
  "Windfall",
  "X",
  "Umma",
  "Alice",
  "Master",
  "Measure of Revenge",
  "The Lost City",
  "Everything Everywhere All at Once",
  "Infinite Storm",
  "7 Days",
  "Moonshot",
  "Morbius",
  "The Bubble",
  "The Contractor",
  "Better Nate Than Ever",
  "Apollo 10 1⁄2: A Space Age Childhood",
  "Sonic the Hedgehog 2",
  "Ambulance",
  "All the Old Knives",
  "Metal Lords",
  "Father Stu",
  "Fantastic Beasts: The Secrets of Dumbledore",
  "Dual",
  "Choose or Die",
  "Titanic 666",
  "The Bad Guys",
  "The Northman",
  "The Unbearable Weight of Massive Talent",
  "Polar Bear",
  "The Survivor",
  "Memory",
  "Crush",
  "Fortress: Sniper's Eye",
  "Green Ghost and the Masters of the Stone",
  "Corrective Measures",
  "Doctor Strange in the Multiverse of Madness",
  "Along for the Ride",
  "Marmaduke",
  "Escape the Field",
  "Operation Mincemeat",
  "Senior Year",
  "Firestarter",
  "Sneakerella",
  "On the Count of Three",
  "Private Property",
  "Family Camp",
  "Montana Story",
  "Vendetta",
  "Downton Abbey: A New Era",
  "Chip 'n Dale: Rescue Rangers",
  "Good Mourning",
  "The Valet",
  "Emergency",
  "Top Gun: Maverick",
  "The Bob's Burgers Movie",
  "Zero Contact",
  "A Chiara",
  "South Park The Streaming Wars",
  "Hollywood Stargirl",
  "Crimes of the Future",
  "Benediction",
  "Interceptor",
  "Fire Island",
  "Watcher",
  "Dashcam",
  "White Elephant",
  "Hustle",
  "Jurassic World Dominion",
  "Jennifer Lopez: Halftime",
  "Father of the Bride",
  "Lightyear",
  "Spiderhead",
  "Jerry & Marge Go Large",
  "Cha Cha Real Smooth",
  "Mid-Century",
  "Abandoned",
  "Beavis and Butt-Head Do the Universe",
  "Elvis",
  "The Black Phone",
  "The Man from Toronto",
  "The Sea Beast",
  "Marcel the Shell with Shoes On",
  "Rise",
  "Press Play",
  "Beauty",
  "Minions: The Rise of Gru",
  "The Forgiven",
  "Mr. Malcolm's List",
  "The Princess",
  "Hot Seat",
  "Hello, Goodbye, and Everything in Between",
  "Thor: Love and Thunder",
  "South Park The Streaming Wars Part 2",
  "The Gray Man",
  "Where the Crawdads Sing",
  "Paws of Fury: The Legend of Hank",
  "Persuasion",
  "Gone in the Night",
  "1Up",
  "Wrong Place",
  "Don't Make Me Go",
  "He's Watching",
  "Nope",
  "Anything's Possible",
  "Alone Together",
  "DC League of Super-Pets",
  "Thirteen Lives",
  "Vengeance",
  "Sharp Stick",
  "Not Okay",
  "Paradise Highway",
  "Resurrection",
  "A Love Song",
  "Honor Society",
  "Allegoria",
  "Bullet Train",
  "Luck",
  "Prey",
  "Easter Sunday",
  "Rise of the Teenage Mutant Ninja Turtles: The Movie",
  "Bodies Bodies Bodies",
  "They/Them",
  "Secret Headquarters",
  "Day Shift",
  "Mack & Rita",
  "Fall",
  "Emily the Criminal",
  "Summering",
  "Beast",
  "Orphan: First Kill",
  "Spin Me Round",
  "Delia's Gone",
  "Three Thousand Years of Longing",
  "Samaritan",
  "Me Time",
  "The Invitation",
  "Breaking",
  "Funny Pages",
  "Honk for Jesus. Save Your Soul.",
  "Gigi & Nate",
  "Wire Room",
  "One Way",
  "After Ever Happy",
  "Pinocchio",
  "Barbarian",
  "End of the Road",
  "Lifemark",
  "Flight/Risk",
  "Clerks III",
  "The Woman King",
  "See How They Run",
  "Blonde",
  "Pearl",
  "Do Revenge",
  "The Silent Twins",
  "Confess, Fletch",
  "Moonage Daydream",
  "God's Country",
  "Goodnight Mommy",
  "Running the Bases",
  "Jeepers Creepers: Reborn",
  "Don't Worry Darling",
  "Catherine Called Birdy",
  "Section Eight",
  "Lou",
  "On the Come Up",
  "A Jazzman's Blues",
  "The Munsters",
  "Smile",
  "Bros",
  "Hocus Pocus 2",
  "The Greatest Beer Run Ever",
  "The Good House",
  "Luckiest Girl Alive",
  "God's Creatures",
  "Dead for a Dollar",
  "My Best Friend's Exorcism",
  "Hot Take: The Depp/Heard Trial",
  "Mr. Harrigan's Phone",
  "Terrifier 2",
  "Lyle, Lyle, Crocodile",
  "Amsterdam",
  "Tár",
  "Hellraiser",
  "Significant Other",
  "The Redeem Team",
  "Halloween Ends",
  "Till",
  "Rosaline",
  "All Quiet on the Western Front",
  "Raymond & Ray",
  "Stars at Noon",
  "The Curse of Bridge Hollow",
  "Bitch Ass",
  "The School for Good and Evil",
  "The Good Nurse",
  "V/H/S/99",
  "Black Adam",
  "Ticket to Paradise",
  "Wendell & Wild",
  "The Banshees of Inisherin",
  "My Policeman",
  "Aftersun",
  "Detective Knight: Rogue",
  "The Return of Tanya Tucker: Featuring Brandi Carlile",
  "Armageddon Time",
  "Call Jane",
  "Causeway",
  "Prey for the Devil",
  "Run Sweetheart Run",
  "The Wonder",
  "The Independent",
  "Enola Holmes 2",
  "My Father's Dragon",
  "Weird: The Al Yankovic Story",
  "The Estate",
  "The Minute You Wake Up Dead",
  "On the Line",
  "Dear Zoe",
  "Something in the Dirt",
  "Good Night Oppy",
  "Guillermo del Toro's Pinocchio",
  "Falling for Christmas",
  "Black Panther: Wakanda Forever",
  "The Fabelmans",
  "Spirited",
  "Is That Black Enough for You?!?",
  "Paradise City",
  "Poker Face",
  "A Christmas Story Christmas",
  "Christmas with You",
  "She Said",
  "The Menu",
  "Disenchanted",
  "Slumberland",
  "Bones and All",
  "The Inspection",
  "Scrooge: A Christmas Carol",
  "Lamborghini: The Man Behind the Legend",
  "The People We Hate at the Wedding",
  "Prancer: A Christmas Tale",
  "Strange World",
  "Glass Onion: A Knives Out Mystery",
  "Devotion",
  "Nanny",
  "A Christmas Mystery",
  "Holiday Harmony",
  "The Noel Diary",
  "White Noise",
  "A Hollywood Christmas",
  "Violent Night",
  "Emancipation",
  "Spoiler Alert",
  "Diary of a Wimpy Kid: Rodrick Rules",
  "Darby and the Dead",
  "Lady Chatterley's Lover",
  "The Eternal Daughter",
  "Matilda the Musical",
  "Empire of Light",
  "Night at the Museum: Kahmunrah Rises Again",
  "The Whale",
  "Something from Tiffany's",
  "Detective Knight: Redemption",
  "The Mean One",
  "5000 Blankets",
  "Avatar: The Way of Water",
  "Puss in Boots: The Last Wish",
  "Wildcat",
  "Babylon",
  "Whitney Houston: I Wanna Dance with Somebody",
  "The Pale Blue Eye",
  "Women Talking",
  "A Man Called Otto",
  "Alice, Darling",
  "M3GAN",
  "The Old Way",
  "The Devil Conspiracy",
  "Plane",
  "House Party",
  "Sick",
  "The Drop",
  "Dog Gone",
  "There's Something Wrong with the Children",
  "Missing",
  "The Son",
  "When You Finish Saving the World",
  "Detective Knight: Independence",
  "Kids vs. Aliens",
  "Teen Wolf: The Movie",
  "You People",
  "Shotgun Wedding",
  "Maybe I Do",
  "Life Upside Down",
  "Fear",
  "Knock at the Cabin",
  "80 for Brady",
  "The Locksmith",
  "Baby Ruby",
  "Freedom's Path",
  "Magic Mike's Last Dance",
  "Sharper",
  "Your Place or Mine",
  "Somebody I Used to Know",
  "Consecration",
  "The Outwaters",
  "Ant-Man and the Wasp: Quantumania",
  "Cocaine Bear",
  "We Have a Ghost",
  "Luther: The Fallen Sun",
  "Jesus Revolution",
  "Bruiser",
  "Linoleum",
  "God's Time",
  "Creed III",
  "Operation Fortune: Ruse de Guerre",
  "A Little White Lie",
  "Children of the Corn",
  "Palm Trees and Power Lines",
  "Hunt Her, Kill Her",
  "Unseen",
  "Scream VI",
  "65",
  "Champions",
  "Chang Can Dunk",
  "Southern Gospel",
  "Shazam! Fury of the Gods",
  "Boston Strangler",
  "The Magician's Elephant",
  "Moving On",
  "Wildflower",
  "Supercell",
  "Pinball: The Man Who Saved the Game",
  "John Wick: Chapter 4",
  "A Good Person",
  "The Tutor",
  "Dungeons & Dragons: Honor Among Thieves",
  "Murder Mystery 2",
  "Tetris",
  "Spinning Gold",
  "Space Oddity",
  "A Thousand and One",
  "Assassin",
  "Acidman",
  "Malum",
  "The Super Mario Bros. Movie",
  "Air",
  "Praise This",
  "Showing Up",
  "Paint",
  "On a Wing and a Prayer",
  "Chupa",
  "How to Blow Up a Pipeline",
  "One True Loves",
  "Beautiful Disaster",
  "Renfield",
  "The Pope's Exorcist",
  "Mafia Mamma",
  "Sweetwater",
  "Rare Objects",
  "Quasi",
  "Evil Dead Rise",
  "The Covenant",
  "Ghosted",
  "Beau Is Afraid",
  "Chevalier",
  "Somewhere in Queens",
  "A Tourist's Guide to Love",
  "Peter Pan & Wendy",
  "Are You There God? It's Me, Margaret",
  "Big George Foreman",
  "Sisu",
  "Guardians of the Galaxy Vol. 3",
  "Book Club: The Next Chapter",
  "Love Again",
  "The Mother",
  "Hypnotic",
  "Crater",
  "Knights of the Zodiac",
  "Monica",
  "Fast X",
  "White Men Can't Jump",
  "Master Gardener",
  "The Little Mermaid",
  "About My Father",
  "The Machine",
  "Kandahar",
  "You Hurt My Feelings",
  "Spider-Man: Across the Spider-Verse",
  "The Boogeyman",
  "Past Lives",
  "Transformers: Rise of the Beasts",
  "Strays",
  "Flamin' Hot",
  "The Flash",
  "Elemental",
  "Asteroid City",
  "Extraction 2",
  "The Blackening",
  "No Hard Feelings",
  "The Perfect Find",
  "Indiana Jones and the Dial of Destiny",
  "Ruby Gillman, Teenage Kraken",
  "Harold and the Purple Crayon",
  "Insidious: The Red Door",
  "Joy Ride",
  "Biosphere",
  "Mission: Impossible – Dead Reckoning Part One",
  "Theater Camp",
  "Oppenheimer",
  "Barbie",
  "They Cloned Tyrone",
  "Cobweb",
  "Haunted Mansion",
  "Sympathy for the Devil",
  "Teenage Mutant Ninja Turtles: Mutant Mayhem",
  "Meg 2: The Trench",
  "Dreamin' Wild",
  "Gran Turismo",
  "The Last Voyage of the Demeter",
  "Heart of Stone",
  "Blue Beetle",
  "White Bird: A Wonder Story",
  "Please Don't Destroy",
  "The Hill",
  "Lift",
  "They Listen",
  "The Equalizer 3",
  "The Nun 2",
  "My Big Fat Greek Wedding 3",
  "A Haunting in Venice",
  "Challengers",
  "The Expendables 4",
  "The Book of Clarence",
  "Next Goal Wins",
  "PAW Patrol: The Mighty Movie",
  "Kraven the Hunter",
  "Killers of the Flower Moon",
  "True Love",
  "Untitled The Exorcist film",
  "Damsel",
  "Ordinary Angels",
  "Dumb Money",
  "The Underdoggs",
  "Five Nights at Freddy's",
  "Saw X",
  "Pain Hustlers",
  "Dune: Part Two",
  "The Marvels",
  "Chicken Run: Dawn of the Nugget",
  "The Killer",
  "The Holdovers",
  "The Hunger Games: The Ballad of Songbirds and Snakes",
  "Trolls Band Together",
  "A Family Affair",
  "Thanksgiving",
  "Wish",
  "Napoleon",
  "Leo",
  "Leave the World Behind",
  "Magazine Dreams",
  "Wonka",
  "Aquaman and the Lost Kingdom",
  "Untitled Ghostbusters: Afterlife sequel",
  "Rebel Moon",
  "Migration",
  "The Color Purple",
];

export async function fetchTitles(searchInput = "") {
  return titles
    .filter((title) => title.toLowerCase().includes(searchInput.toLowerCase()))
    .slice(0, 10);
}
